version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_HOST: ${POSTGRES_HOST}
      TZ: ${TZ}
    container_name: postgres-db
    ports:
      #      - "127.0.0.1:5432:5432"
      - "5432:5432" # open host for superset purposes
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  nestjs:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: bot-whats-ap
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_HOST: db
      ROOT_TOCEN: ${ROOT_TOCEN}
      ROOT_INSTANS: ${ROOT_INSTANS}
      TZ: ${TZ}
    ports:
      - "3000:3000" # expose-to-the-world : only-in-the-docker
    container_name: nest-todo-app-be
    restart: always
    depends_on:
      - db
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
volumes:
  db-data:
    driver: local

