version: "3"
services:

  postgres:
    container_name: 'watsap_postgres'
    image: postgres
    ports:
#      - "127.0.0.1:5432:5432"
      - "0.0.0.0:5432:5432" # open host for superset purposes
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - ./db-data:/var/lib/postgresql/data
volumes:
  db-data:
    driver: local
