export enum ActionType {
  TEMPLATE_REGISTRATION = 'TEMPLATE_REGISTRATION',
  REGISTRATION = 'REGISTRATION',
  TEMPLATE_USER_MESSAGE = 'TEMPLATE_USER_MESSAGE',
  USER_MESSAGE = 'USER_MESSAGE',
  NULL = '',
  TEMPLATE_ADD_CHAT = 'TEMPLATE_ADD_CHAT',
  HELP = 'HELP',
}
